config/routes.rb
Rails.application.routes.draw do
  resources :teams do
    collection do
      get :index2
    end
  end
  resources :racers do
    collection do
      get :search
      get :example
      get :index2
    end
  end

  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

  resources :calendar_of_the_championships do
    collection do
      get :index2
    end
  end

end

app/models/racer.rb
class Racer < ActiveRecord::Base
  has_many :teams1, class_name: 'Team', foreign_key: 'racer1_id'
  has_many :teams2, class_name: 'Team', foreign_key: 'racer2_id'

  validates :surname, :firstname, :bday, :country, :number_of_wins, presence: true

  def self.search(params)
    # result=Racer.joins(:teams1)+Racer.joins(:teams2)
    result = Racer.includes(:teams1,:teams2).references(:teams1,:teams2)

    if params['surname'].present?
      result=result.where(surname: params['surname'])
    end
    if params['firstname'].present?
      result=result.where(firstname: params['firstname'])
    end
    if params['bday'].present?
      result=result.where(bday: params['bday'])
    end
    if params['country'].present?
      result=result.where(country: params['country'])
    end
    if params['number_of_wins'].present?
      result=result.where(number_of_wins: params['number_of_wins'])
    end
    # if params['team_name'].present?
    #    (result.where(teams: {racer1_id: params['racer1_id']}))
    # end
    if  (params['racer1_id'].present?) and (params['racer2_id'].present?)
      result=[]
    elsif  (params['racer1_id'].present?)
      result= result.where.not(teams: {racer1_id: nil})
    elsif  (params['racer2_id'].present?)
      result= result.where.not(teams2s_racers: {racer2_id: nil})

    end
    if params['team_name'].present?
      result= result.where(teams2s_racers: {team_name: params['team_name']}) +
       (result.where(teams: {team_name: params['team_name']}))
    end
    if params['motor_manufacturer'].present?
      result= result.where(teams2s_racers: {motor_manufacturer: params['motor_manufacturer']}) +
       (result.where(teams: {motor_manufacturer: params['motor_manufacturer']}))
    end
    if params['car_number1'].present?
      result= (result.where(teams: {car_number1: params['car_number1']})) +
       (result.where(teams2s_racers: {car_number2: params['car_number1']}))
    end
    if params['team_country'].present?
      result= result.where(teams2s_racers: {team_country: params['team_country']}) +
       (result.where(teams: {team_country: params['team_country']}))
    end

    result
  end

end

app/controllers/racers_controller.rb
class RacersController < ApplicationController
  before_action :set_racer, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index2, :search]
  skip_before_action :check_app_auth, only: [:index2, :search ]
  before_action -> {check_role('admin', 'operator')}, except: [:index2, :search]
  # GET /racers
  # GET /racers.json
  def index
    @racers = Racer.all
  end
  def example
    @countries=[]
    (Racer.all).each do |r|
      if !(@countries.include?(r.country))
        @countries<<r.country
      end

    end
    @motor_manufacturers=[]

    @teams= []
    @n1<<t.car_number1
    @n1<<t.car_number2
    @team_countries=[]
    (Team.all).each do |t|
      @motor_manufacturers<<t.motor_manufacturer
      @n1<<t.car_number1
      @n2<<t.car_number2
      @team_countries<<t.team_country

    end
    @motor_manufacturers=@motor_manufacturers.uniq
    @team_countries= @team_countries.uniq



    (Racer.all).each do |r|
      if !(@teams.include?(r.teams1.first.try(:team_name)))
        @teams<<(r.teams1[0]).try(:team_name)
      end
      if !(@teams.include?(r.teams2.first.try(:team_name)))
        @teams<<(r.teams2[0]).try(:team_name)
      end
    @teams.compact!
    end
    if params.has_key?('search')
      @racers=Racer.search(params['search'])
    else
      @racers=[]
    end
    params['search'] ||= {}
  end
  def index2
    @racers = Racer.all
  end

  def search
    @countries=[]
    (Racer.all).each do |r|
      if !(@countries.include?(r.country))
        @countries<<r.country
      end

    end
    @motor_manufacturers=[]

    @teams= []
    @n1=[]
    @n2=[]
    @team_countries=[]
    (Team.all).each do |t|
      @motor_manufacturers<<t.motor_manufacturer
      @n1<<t.car_number1
      @n1<<t.car_number2
      @team_countries<<t.team_country

    end
    @motor_manufacturers=@motor_manufacturers.uniq
    @team_countries= @team_countries.uniq



    (Racer.all).each do |r|
      if !(@teams.include?(r.teams1.first.try(:team_name)))
        @teams<<(r.teams1[0]).try(:team_name)
      end
      if !(@teams.include?(r.teams2.first.try(:team_name)))
        @teams<<(r.teams2[0]).try(:team_name)
      end
    @teams.compact!
    end
    if params.has_key?('search')
      @racers=Racer.search(params['search'])
    else
      @racers=[]
    end
    params['search'] ||= {}
  end

  # GET /racers/1
  # GET /racers/1.json
  def show
  end

  # GET /racers/new
  def new
    @racer = Racer.new
  end

  # GET /racers/1/edit
  def edit
  end

  # POST /racers
  # POST /racers.json
  def create
    @racer = Racer.new(racer_params)

    respond_to do |format|
      if @racer.save
        format.html { redirect_to @racer, notice: 'Racer was successfully created.' }
        format.json { render :show, status: :created, location: @racer }
      else
        format.html { render :new }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /racers/1
  # PATCH/PUT /racers/1.json
  def update
    respond_to do |format|
      if @racer.update(racer_params)
        format.html { redirect_to @racer, notice: 'Racer was successfully updated.' }
        format.json { render :show, status: :ok, location: @racer }
      else
        format.html { render :edit }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /racers/1
  # DELETE /racers/1.json
  def destroy
    @racer.destroy
    respond_to do |format|
      format.html { redirect_to racers_url, notice: 'Racer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_racer
      @racer = Racer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def racer_params
      params.require(:racer).permit(:surname, :firstname, :bday, :country, :number_of_wins)
    end
end

app/helpers/racers_helper.rb
module RacersHelper
end

app/views/racers/_form.html.haml
= form_for @racer do |f|
  - if @racer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@racer.errors.count, "error")} prohibited this racer from being saved:"
      %ul
        - @racer.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :surname
    = f.text_field :surname
  .field
    = f.label :firstname
    = f.text_field :firstname
  .field
    = f.label :bday
    = f.date_select :bday
  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :number_of_wins
    = f.number_field :number_of_wins
  .actions
    = f.submit 'Сохранить', class: "btn btn-primary"

app/views/racers/edit.html.haml
%h1=t('headers.racers.index')
= render 'form'

= link_to 'Показать', @racer, class: "btn btn-primary"
= link_to 'Назад', racers_path, class: "btn btn-primary"

app/views/racers/example.html.haml
%table
  %thead
    %tr
      %th Payment
      %th Issue data
      %th Amount
      %th Period
  %tbody
    %tr
      %td{:data => {:label => "Payment"}}
        Payment #1
      %td{:data => {:label => "Issue data"}}
        02/01/2015
      %td{:data => {:label => "Amount"}}
        $2,311
      %td{:data => {:label => "Period"}}
        01/01/2015 - 01/31/2015
    %tr
      %td{:data => {:label => "Payment"}}
        Payment #2
      %td{:data => {:label => "Issue data"}}
        03/01/2015
      %td{:data => {:label => "Amount"}}
        $3,211
      %td{:data => {:label => "Period"}}
        02/01/2015 - 02/28/2015



= form_tag search_racers_path(), method: :get do
  .well
    .row
      .col-md-5.c
        .row
          .col-md-12.my_head
            Поиск по атрибутам пилота
        .row
          .col-md-12.simple
            .form-group
              = label_tag 'search[surname]','Фамилия'
              = text_field_tag 'search[surname]', params['search']['surname'], class: 'form-control'
        .row
          .col-md-12.simple
            .form-group
              = label_tag 'search[firstname]','Имя'
              =text_field_tag 'search[firstname]', params['search']['firstname'], class: 'form-control'
        .row
          .col-md-12.simple
            .form-group
              =label_tag 'search[bday]','Дата рождения'
              %dd
                %div
                  .input-group.data.datapicker
                    =text_field_tag 'search[bday]', params['search']['bday'], class: 'form-control'
                    %span.input-group-addon
                      %span.glyphicon.glyphicon-calendar
        .row
          .col-md-12.simple
            .form-group
              = label_tag 'search[country]','Место рождения'
              =select_tag 'search[country]',  options_for_select(@countries),{ include_blank: true, class: 'form-control'}
        .row
          .col-md-12.simple
            .form-group
              =label_tag 'search[number_of_wins]','Количество побед'
              =text_field_tag 'search[number_of_wins]', params['search']['number_of_wins'], class: 'form-control'
        .row
          .col-md-12.simple
            .form-group
              =submit_tag 'Искть'

      .col-md-1

      .col-md-5.my_head.c
        .row
          .col-md-12.my_head
            Поиск по атрибутам команды
        .row
          .col-md-12.simple
            .form-group
              = label_tag 'search[team_name]','Название команды'
              =select_tag 'search[team_name]',  options_for_select(@teams),{ include_blank: true, class: 'form-control'}
        .row
          .col-md-12.simple
            .form-group
              = label_tag 'search[motor_manufacturer]','Производитель мотора'
              =select_tag 'search[motor_manufacturer]',  options_for_select(@motor_manufacturers),{ include_blank: true, class: 'form-control'}
        .row
          .col-md-12.simple
            .form-group
              = label_tag 'search[car_number1]','Номер машины первого гонщика'
              =select_tag 'search[car_number1]',  options_for_select(@n1),{ include_blank: true, class: 'form-control'}

        .row
          .col-md-12.simple
            .form-group
              = label_tag 'search[car_number2]','Номер машины второго гонщика'
              =select_tag 'search[car_number2]', options_for_select(@n2),{ include_blank: true, class: 'form-control'}
        .row
          .col-md-12.simple
            .form-group
              = label_tag 'search[team_country]','Страна команды'
              =select_tag 'search[team_country]', options_for_select(@team_countries),{ include_blank: true, class: 'form-control'}
        .row
          .col-md-12.simple
            .form-group
              = label_tag 'search[racer1_id]','Является первым гонщиком'
              =check_box_tag 'search[racer1_id]'
        .row
          .col-md-12.simple
            .form-group
              = label_tag 'search[racer2_id]','Является вторым гонщиком'
              =check_box_tag 'search[racer2_id]'


-# %h2 Результаты поиска
-# %table.responstable
-#   %tr
-#     %th №
-#     %th{:data => {:th => "Driver details"}}}
-#       %span
-#         First name
-#     %th
-#       Surname
-#     %th
-#       Surname data of birth
-#     %th
-#       Relationship
-#   %tr
-#     %td
-#       1
-#     %td  Steve
-#     %td Foo
-#     %td 01/01/1978
-#     %td Policyholder
-#   %tr
-#     %td 2
-#     %td Steffie
-#     %td Foo
-#     %td 01/01/1978
-#     %td Spouse

-# %table{class: "rwd-table"}}
-#   %tr
-#     %th
-#       Movie Title
-#     %th
-#       Genre
-#     %th
-#       Year
-#     %th
-#       Gross
-#   %tr
-#     %td {:data => {th: "Movie Title"}}}
-#       Star Wars
-#     %td {:data => {th: "Genre"}}}
-#       Adventure, Sci-fi
-#     %td {:data => {th: "Year"}}}
-#       1977
-#     %td {:data => {th: "Gross"}}}
-#       $460,935,665
-#   %tr
-#     %td {:data => {:th => "Movie Title"}}}
-#       Howard The Duck
-#     %td {:data => {:th => "Genre"}}}
-#       Comedy
-#     %td {:data => {:th => "Year"}}}
-#       1986
-#     %td {:data => {:th => "Gross"}}}
-#       $16,295,774
-#   %tr
-#     %td {:data => {:th => "Movie Title"}}}
-#       American Graffiti
-#     %td {:data => {:th => "Genre"}}}
-#       Comedy, Drama
-#     %td {:data => {:th => "Year"}}}
-#       1973
-#     %td {:data => {:th => "Gross"}}}
-#       $115,000,000

  %table.table.table-hover.table-striped.table-responsive
    %thead
      %tr
        %th= Racer.human_attribute_name(:surname)
        %th= Racer.human_attribute_name(:firstname)
        %th= Racer.human_attribute_name(:bday)
        %th= Racer.human_attribute_name(:country)
        %th= Racer.human_attribute_name(:number_of_wins)
    %tbody
      - @racers.each do |racer|
        %tr
          %td = racer.surname
          %td = racer.firstname
          %td = racer.bday
          %td = racer.country
          %td = racer.number_of_wins

app/views/racers/index.html.haml
%h1= t('headers.racers.index')
%table.table-striped.table-hover
  %caption
    = link_to new_racer_path, class: 'btn btn-success' do
      = fa_icon :plus
      = t('buttons.new.racer')
  %thead
    %tr
      %th= Racer.human_attribute_name(:surname)
      %th= Racer.human_attribute_name(:firstname)
      %th= Racer.human_attribute_name(:bday)
      %th= Racer.human_attribute_name(:country)
      %th= Racer.human_attribute_name(:number_of_wins)
      %th

  %tbody
    - @racers.each do |racer|
      %tr
        %td{:data => {:label => (Racer.human_attribute_name(:surname))}}
          = racer.surname
        %td{:data => {:label => (Racer.human_attribute_name(:firstname))}}
          = racer.firstname
        %td{:data => {:label => (Racer.human_attribute_name(:bday))}}
          = racer.bday
        %td{:data => {:label => (Racer.human_attribute_name(:country))}}
          = racer.country
        %td{:data => {:label => (Racer.human_attribute_name(:number_of_wins))}}
          = racer.number_of_wins
        %td.right
          = link_to racer, class: 'btn btn-warning' do
            = fa_icon :eye
            = t('buttons.show')
          = link_to edit_racer_path(racer), class: 'btn btn-info' do
            = fa_icon :edit
            = t('buttons.edit')
          = link_to racer, :method => :delete,
          :data => { :confirm => t('buttons.confirm.racer') },
          class: 'btn btn-danger' do
            = fa_icon :times
            = t('buttons.destroy')

app/views/racers/index2.html.haml
%h1= t('headers.racers.index')
%table.table-striped.table-hover
  %thead
    %tr
      %th= Racer.human_attribute_name(:surname)
      %th= Racer.human_attribute_name(:firstname)
      %th= Racer.human_attribute_name(:bday)
      %th= Racer.human_attribute_name(:country)
      %th= Racer.human_attribute_name(:number_of_wins)

  %tbody
    - @racers.each do |racer|
      %tr
        %td{:data => {:label => (Racer.human_attribute_name(:surname))}}
          = racer.surname
        %td{:data => {:label => (Racer.human_attribute_name(:firstname))}}
          = racer.firstname
        %td{:data => {:label => (Racer.human_attribute_name(:bday))}}
          = racer.bday
        %td{:data => {:label => (Racer.human_attribute_name(:country))}}
          = racer.country
        %td{:data => {:label => (Racer.human_attribute_name(:number_of_wins))}}
          = racer.number_of_wins

app/views/racers/new.html.haml
%h1=t('headers.racer.new')

= render 'form'

= link_to 'Назад', racers_path, class: "btn btn-primary"

app/views/racers/search.html.haml
= form_tag search_racers_path(), method: :get do
  .well
    .row
      .col-md-5.c
        .row
          .col-md-12.simple
            .form-group
              = label_tag 'search[surname]','Фамилия'
              = text_field_tag 'search[surname]', params['search']['surname'], class: 'form-control'
        .row
          .col-md-12.simple
            .form-group
              = label_tag 'search[firstname]','Имя'
              =text_field_tag 'search[firstname]', params['search']['firstname'], class: 'form-control'
        .row
          .col-md-12.simple
            .form-group
              =label_tag 'search[bday]','Дата рождения'
              %dd
                %div
                  .input-group.date.datepicker
                    =text_field_tag 'search[bday]', params['search']['bday'], class: 'form-control'
                    %span.input-group-addon
                      %span.glyphicon.glyphicon-calendar
        .row
          .col-md-12.simple
            .form-group
              = label_tag 'search[country]','Место рождения'
              =select_tag 'search[country]',  options_for_select(@countries),{ include_blank: true, class: 'form-control'}
        .row
          .col-md-12.simple
            .form-group
              =label_tag 'search[number_of_wins]','Количество побед'
              =text_field_tag 'search[number_of_wins]', params['search']['number_of_wins'], class: 'form-control'
        .row
          .col-md-12.simple
            .form-group
              =submit_tag 'Искать', class: 'btn btn-danger'


- if  @racers.size>0
  %h2 Результаты поиска
  %table
    %thead
      %tr
        %th= Racer.human_attribute_name(:surname)
        %th= Racer.human_attribute_name(:firstname)
        %th= Racer.human_attribute_name(:bday)
        %th= Racer.human_attribute_name(:country)
        %th= Racer.human_attribute_name(:number_of_wins)
    %tbody
      - @racers.each do |racer|
        %tr
          %td{:data => {:label => (Racer.human_attribute_name(:surname))}}
            = racer.surname
          %td{:data => {:label => (Racer.human_attribute_name(:firstname))}}
            = racer.firstname
          %td{:data => {:label => (Racer.human_attribute_name(:bday))}}
            = racer.bday
          %td{:data => {:label => (Racer.human_attribute_name(:country))}}
            = racer.country
          %td{:data => {:label => (Racer.human_attribute_name(:number_of_wins))}}
            = racer.number_of_wins




-# .row
-#   .col-md-2.head
-#     =Racer.human_attribute_name(:surname)
-#   .col-md-2.head
-#     =Racer.human_attribute_name(:firstname)
-#   .col-md-2.head
-#     =Racer.human_attribute_name(:bday)
-#   .col-md-2.head
-#     =Racer.human_attribute_name(:country)
-#   .col-md-2.head
-#     =Racer.human_attribute_name(:number_of_wins)
-# - @racers.each do |racer|
-#     .row
-#       .col-md-2.head
-#         =racer.surname
-#       .col-md-2.head
-#           =racer.firstname
-#       .col-md-2.head
-#           =racer.bday
-#       .col-md-2.head
-#           =racer.country
-#       .col-md-2.head
-#           =racer.number_of_wins


-# = form_tag search_racers_path(), method: :get do
-#   .row
-#     .col-md-6
-#       .form-group
-#         = label_tag 'search[surname]','Фамилия'
-#         = text_field_tag 'search[surname]', params['search']['surname'], class: 'form-control'
-#     .col-md-6
-#       .form-group
-#         = label_tag 'search[team_name]','Название команды'
-#         =select_tag 'search[team_name]',  options_for_select(@teams),{ include_blank: true, class: 'form-control'}
-#   .row
-#     .col-md-6
-#       .form-group
-#         = label_tag 'search[firstname]','Имя'
-#         =text_field_tag 'search[firstname]', params['search']['firstname'], class: 'form-control'
-#
-#
-#   .row
-#     .col-md-6
-#       .form-group
-#         =label_tag 'search[bday]','Дата рождения'
-#         %dd
-#           %div
-#             .input-group.date.datepicker
-#               =text_field_tag 'search[bday]', params['search']['bday'], class: 'form-control'
-#               %span.input-group-addon
-#                 %span.glyphicon.glyphicon-calendar
-#
-#
-#   .row
-#     .col-md-6
-#       .form-group
-#         = label_tag 'search[country]','Место рождения'
-#         =select_tag 'search[country]',  options_for_select(@countries),{ include_blank: true, class: 'form-control'}
-#
-#   .row
-#     .col-md-6
-#       .form-group
-#         =label_tag 'search[number_of_wins]','Количество побед'
-#         =text_field_tag 'search[number_of_wins]', params['search']['number_of_wins'], class: 'form-control'
-#     .col-md-6
-#       .form-group
-#         = label_tag 'search[team_country]','Страна команды'
-#         =select_tag 'search[team_country]', options_for_select(@team_countries),{ include_blank: true, class: 'form-control'}
-#   %hr
-#   %h2 Результаты поиска
-#
-#   %table.table.table-hover.table-striped.table-responsive
-#     %thead
-#       %tr
-#         %th= Racer.human_attribute_name(:surname)
-#         %th= Racer.human_attribute_name(:firstname)
-#         %th= Racer.human_attribute_name(:bday)
-#         %th= Racer.human_attribute_name(:country)
-#         %th= Racer.human_attribute_name(:number_of_wins)
-#     %tbody
-#       - @racers.each do |racer|
-#         %tr
-#           %td= racer.surname
-#           %td= racer.firstname
-#           %td= racer.bday
-#           %td= racer.country
-#           %td= racer.number_of_wins

app/views/racers/show.html.haml
%h1= @racer.surname+@racer.try(:firstname)
%dl
  %dt= Racer.human_attribute_name(:surname)
  %dd=  @racer.surname

  %dt= Racer.human_attribute_name(:firstname)
  %dd=  @racer.firstname

  %dt= Racer.human_attribute_name(:bday)
  %dd=  @racer.bday

  %dt= Racer.human_attribute_name(:country)
  %dd=  @racer.country

  %dt= Racer.human_attribute_name(:number_of_wins)
  %dd=  @racer.number_of_wins

= link_to 'Редактировать', edit_racer_path(@racer), class: "btn btn-primary"
= link_to 'Назад', racers_path, class: "btn btn-primary"